CREATE OR REPLACE WAREHOUSE ETL_WH 
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE ETL_WH;

CREATE OR REPLACE DATABASE RETAIL_DW;
USE DATABASE RETAIL_DW;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;

-- CREATE A FILE FORMAT
CREATE OR REPLACE FILE FORMAT RETAIL_DW.SILVER.CSV_FF
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = (' ', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;

-- CREATE AN EXTERNAL STAGE
CREATE OR REPLACE STAGE RETAIL_DW.SILVER.BRONZE_STAGE
    URL = 's3://retail-transactions/transactions.csv'
    CREDENTIALS = '***'
    FILE_FORMAT = RETAIL_DW.SILVER.CSV_FF;




LIST @RETAIL_DW.SILVER.BRONZE_STAGE;


USE SCHEMA RETAIL_DW.SILVER;


CREATE OR REPLACE TABLE ORDERS(
    TRANSACTION_ID STRING,
    ORDER_TIMESTAMP TIMESTAMP,
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    PRODUCT_NAME STRING,
    PRODUCT_CATEGORY STRING,
    QUANTITY NUMBER,
    PRICE FLOAT,
    TOTAL_AMOUNT FLOAT,
    PAYMENT_METHOD STRING,
    STORE_LOCATION STRING
);


COPY INTO RETAIL_DW.SILVER.ORDERS
FROM @RETAIL_DW.SILVER.BRONZE_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FF)
ON_ERROR = 'ABORT_STATEMENT';


    