
USE WAREHOUSE ETL_WH;
USE DATABASE RETAIL_DW;


MERGE INTO RETAIL_DW.GOLD.DIM_CUSTOMER tgt
USING (
    SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME, STORE_LOCATION
    FROM RETAIL_DW.SILVER.ORDERS
) src
ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
WHEN MATCHED AND (tgt.CUSTOMER_NAME <> src.CUSTOMER_NAME 
               OR tgt.STORE_LOCATION <> src.STORE_LOCATION) THEN
  UPDATE SET
    CUSTOMER_NAME = src.CUSTOMER_NAME,
    STORE_LOCATION = src.STORE_LOCATION
WHEN NOT MATCHED THEN
  INSERT (CUSTOMER_ID, CUSTOMER_NAME, STORE_LOCATION)
  VALUES (src.CUSTOMER_ID, src.CUSTOMER_NAME, src.STORE_LOCATION);



MERGE INTO RETAIL_DW.GOLD.DIM_PRODUCT tgt
USING (
    SELECT DISTINCT
        MD5(PRODUCT_NAME || PRODUCT_CATEGORY || PRICE) AS PRODUCT_ID,
        PRODUCT_NAME, PRODUCT_CATEGORY, PRICE
    FROM RETAIL_DW.SILVER.ORDERS
) src
ON tgt.PRODUCT_ID = src.PRODUCT_ID
WHEN NOT MATCHED THEN
  INSERT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, PRICE)
  VALUES (src.PRODUCT_ID, src.PRODUCT_NAME, src.PRODUCT_CATEGORY, src.PRICE);




MERGE INTO RETAIL_DW.GOLD.DIM_PAY tgt
USING (
    SELECT DISTINCT MD5(PAYMENT_METHOD) AS PAY_ID, PAYMENT_METHOD
    FROM RETAIL_DW.SILVER.ORDERS
) src
ON tgt.PAYMENT_ID = src.PAYMENT_ID
WHEN NOT MATCHED THEN
  INSERT (PAY_ID, PAYMENT_METHOD)
  VALUES (src.PAY_ID, src.PAYMENT_METHOD);




MERGE INTO RETAIL_DW.GOLD.FACT_ORDERS tgt
USING (
    SELECT
        TRANSACTION_ID,
        ORDER_TIMESTAMP,
        CUSTOMER_ID,
        MD5(PRODUCT_NAME || PRODUCT_CATEGORY || PRICE) AS PRODUCT_ID,
        QUANTITY,
        TOTAL_AMOUNT,
        MD5(PAYMENT_METHOD) AS PAY_ID
    FROM RETAIL_DW.SILVER.ORDERS
) src
ON tgt.TRANSACTION_ID = src.TRANSACTION_ID
WHEN NOT MATCHED THEN
  INSERT (TRANSACTION_ID, ORDER_TIMESTAMP, CUSTOMER_ID, PRODUCT_ID,
          QUANTITY, TOTAL_AMOUNT, PAY_ID)
  VALUES (src.TRANSACTION_ID, src.ORDER_TIMESTAMP, src.CUSTOMER_ID,
          src.PRODUCT_ID, src.QUANTITY, src.TOTAL_AMOUNT, src.PAY_ID);



SELECT COUNT(*) FROM RETAIL_DW.GOLD.FACT_ORDERS;

SELECT COUNT(*) FROM RETAIL_DW.GOLD.DIM_CUSTOMER;

SELECT COUNT(*) FROM RETAIL_DW.GOLD.DIM_PRODUCT;
          