USE WAREHOUSE ETL_WH;
USE DATABASE RETAIL_DW;

USE SCHEMA GOLD;

DESCRIBE TABLE RETAIL_DW.SILVER.ORDERS;

USE SCHEMA GOLD;

CREATE OR REPLACE TABLE DIM_CUSTOMER(
    CUSTOMER_ID STRING PRIMARY KEY,
    CUSTOMER_NAME STRING,
    STORE_LOCATION STRING
);

CREATE OR REPLACE TABLE DIM_PRODUCT(
    PRODUCT_ID STRING PRIMARY KEY,
    PRODUCT_NAME STRING,
    PRODUCT_CATEGORY STRING,
    PRICE FLOAT
    
);

CREATE OR REPLACE TABLE DIM_PAY(
    PAYMENT_ID STRING PRIMARY KEY,
    PAYMENT_METHOD STRING
);


CREATE OR REPLACE TABLE FACT_ORDERS(
    TRANSACTION_ID STRING,
    ORDER_TIMESTAMP TIMESTAMP,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY NUMBER,
    TOTAL_AMOUNT FLOAT,
    PAYMENT_ID STRING,
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
    CONSTRAINT FK_payment_ID FOREIGN KEY (PAYMENT_ID) REFERENCES DIM_pay (PAYMENT_ID)
    );


    